### ISSUE TITLE
Support -t automatic for "node attribute get"

### ISSUE THREAD

**Issue by mcsurly** [pdf/knife-attribute#3]
This should be very simple to implement.
I want to be able to display specific -t automatic entries without resorting to not specifying -t at all (which does the merge and includes -t default stuff as well)
If this is as easy as adding 'automatic' to the typemap, i will do it and submit a pull request.

**Comment by mcsurly** [comment]
With knife-attribute version 1.0.4 from supermarket, and chefdk 1.3.43-1.el7 on my Fedora box, I have made this change and it works perfectly.
Added line 37 in knife-attribute-1.0.4/lib/knife-attribute/node/helpers.rb
              automatic: :automatic_attrs,
I preserved the trailing comma, since the old last element (override) had a trailing comma.

knife node attribute get mynode etc.passwd.root -t automatic
works perfectly.

**Comment by pdf** [comment]
This seems like a fair addition, I'll try and get this committed and pushed out in the next day or so.

**Comment by mcsurly** [comment]
Thanks in advance!

**Comment by pdf** [comment]
I took a slightly different approach to only enable automatic attrs on `get`, since other operations should not be valid for automatically populated values.

I'll be publishing a new release shortly.
